service: lambda-lighthouse-metrics

frameworkVersion: "=1.49.0"

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:${self:provider.region}:*:*'

package:
  individualy: true

functions:
  initialize:
    handler: handler.initialize
    memorySize: 2048
    timeout: 30
    reservedConcurrency: 3

resources:
  Resources:
    pagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: '${self:service.name}-${self:provider.stage}-pages'
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: pageId
            AttributeType: S
        KeySchema:
          - AttributeName: pageId
            KeyType: HASH
    jobsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: '${self:service.name}-${self:provider.stage}-jobs'
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: jobId
            AttributeType: S
        KeySchema:
          - AttributeName: jobId
            KeyType: HASH
    runsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: '${self:service.name}-${self:provider.stage}-runs'
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: pageId
            AttributeType: S
          - AttributeName: jobId
            AttributeType: S
          - AttributeName: runId
            AttributeType: S
        KeySchema:
          - AttributeName: runId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: pageIdIndex
            KeySchema:
              - AttributeName: pageId
                KeyType: HASH
            Projection:
              ProjectionType: KEYS_ONLY
          - IndexName: jobIdIndex
            KeySchema:
              - AttributeName: jobId
                KeyType: HASH
            Projection:
              ProjectionType: KEYS_ONLY
